"""Business, derature_time

Revision ID: 09dc89ac6100
Revises: 5e45d793eaa9
Create Date: 2025-12-18 16:56:16.374172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dc89ac6100'
down_revision: Union[str, None] = '5e45d793eaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sbp_phone_number', sa.String(length=20), nullable=True))
    op.drop_column('users', 'spb_phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spb_phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('users', 'sbp_phone_number')
    # ### end Alembic commands ###
