"""add Referral, trips.additional_info

Revision ID: 5205ce6d3b1a
Revises: e8fc111b71c1
Create Date: 2025-11-04 18:27:38.474301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5205ce6d3b1a'
down_revision: Union[str, None] = 'e8fc111b71c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.add_column('trip_responses', sa.Column('proposed_price', sa.Float(), nullable=True))
    op.add_column('trips', sa.Column('channel_message_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('additional_info', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'additional_info')
    op.drop_column('trips', 'channel_message_id')
    op.drop_column('trip_responses', 'proposed_price')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
