"""- fin oper type

Revision ID: 5e45d793eaa9
Revises: 935c96ab0c87
Create Date: 2025-11-11 20:30:41.938064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e45d793eaa9'
down_revision: Union[str, None] = '935c96ab0c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_operations', 'operation_type',
               existing_type=postgresql.ENUM('DRIVER_SUBSCRIPTION', 'DRIVER_COMMISSION', 'AGENT_COMMISSION', 'PAYOUT', 'DELEGATION_COMMISSION', name='financialoperationtype'),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_operations', 'operation_type',
               existing_type=sa.String(length=255),
               type_=postgresql.ENUM('DRIVER_SUBSCRIPTION', 'DRIVER_COMMISSION', 'AGENT_COMMISSION', 'PAYOUT', 'DELEGATION_COMMISSION', name='financialoperationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
