"""Fin operations, new process of payment

Revision ID: 935c96ab0c87
Revises: f58b0f9b0501
Create Date: 2025-11-11 16:54:41.807036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935c96ab0c87'
down_revision: Union[str, None] = 'f58b0f9b0501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_operations', sa.Column('telegram_payment_charge_id', sa.String(length=255), nullable=True))
    op.add_column('financial_operations', sa.Column('provider_payload', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_operations', 'provider_payload')
    op.drop_column('financial_operations', 'telegram_payment_charge_id')
    # ### end Alembic commands ###
