"""back populate, foreign_key referrals

Revision ID: b43c2cd9b5da
Revises: 5205ce6d3b1a
Create Date: 2025-11-04 19:29:01.076730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43c2cd9b5da'
down_revision: Union[str, None] = '5205ce6d3b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_referral_id', 'referrals', ['referral_id'], unique=False)
    op.create_index('idx_referrer_id', 'referrals', ['referrer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_referrer_id', table_name='referrals')
    op.drop_index('idx_referral_id', table_name='referrals')
    # ### end Alembic commands ###
