"""Initial tables

Revision ID: e8fc111b71c1
Revises: 
Create Date: 2025-10-31 22:55:57.393509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8fc111b71c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('passenger_phone_number', sa.String(length=20), nullable=True))
    op.drop_column('trips', 'passenger_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('passenger_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('trips', 'passenger_phone_number')
    # ### end Alembic commands ###
