"""FinancialOperationType, Users

Revision ID: f58b0f9b0501
Revises: b43c2cd9b5da
Create Date: 2025-11-06 20:53:46.789115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58b0f9b0501'
down_revision: Union[str, None] = 'b43c2cd9b5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('financial_operations_trip_id_fkey', 'financial_operations', type_='foreignkey')
    op.drop_column('financial_operations', 'trip_id')
    op.add_column('users', sa.Column('subscription_exp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('sbp_bank', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('spb_phone_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('organization', sa.String(length=200), nullable=True))
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'organization')
    op.drop_column('users', 'spb_phone_number')
    op.drop_column('users', 'sbp_bank')
    op.drop_column('users', 'subscription_exp')
    op.add_column('financial_operations', sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('financial_operations_trip_id_fkey', 'financial_operations', 'trips', ['trip_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
